name: TopVoter
version: '${version}'
main: dev.jsinco.topvoter.TopVoter
api-version: '1.20'
author: Jsinco
softdepend: [PlaceholderAPI]
folia-supported: true
commands:
  voterreset:
    description: 'Resets the votes'
    permission: 'topvoter.admin'
